import { execSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwind from '@tailwindcss/vite';
import { VitePWA } from 'vite-plugin-pwa';

// Build-time version stamp. The package version is the human-facing label;
// the short git sha + build time make every deploy uniquely identifiable so
// the service worker's "new version → push update" flow has something to show.
// Git sha is best-effort: CI checkouts and the LAN autodeploy box have git,
// but a tarball build (no .git) must still succeed — hence the try/catch.
const require = createRequire(import.meta.url);
const pkgVersion: string = require('./package.json').version ?? '0.0.0';
let gitSha = 'nogit';
try {
  gitSha = execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
    .toString()
    .trim();
} catch {
  /* no git available — fall back to the placeholder */
}
const buildTime = new Date().toISOString();
const appVersion = `${pkgVersion}+${gitSha}`;

export default defineConfig({
  // Exposed to both the app bundle AND the service worker build — vite-plugin-pwa
  // forwards `define` into its injectManifest compile, so sw.ts can read these.
  define: {
    __APP_VERSION__: JSON.stringify(appVersion),
    __BUILD_TIME__: JSON.stringify(buildTime),
  },
  plugins: [
    react(),
    tailwind(),
    VitePWA({
      strategies: 'injectManifest',
      srcDir: 'src',
      filename: 'sw.ts',
      // 'prompt' (not 'autoUpdate') because we drive the update ourselves from
      // lib/pwa.ts: when a new SW is waiting we show a toast, then auto-apply.
      // autoUpdate's bundled reload-on-controllerchange would race our toast.
      registerType: 'prompt',
      // We register manually via `virtual:pwa-register` in lib/pwa.ts so we get
      // the onNeedRefresh / onOfflineReady hooks and a periodic update poll —
      // the auto-injected <script> gives none of that.
      injectRegister: false,
      injectManifest: {
        // webm covers the tiny demo-video used by the PiP demo so it plays offline.
        globPatterns: ['**/*.{js,css,html,svg,png,ico,webmanifest,webm}'],
      },
      devOptions: {
        enabled: true,
        type: 'module',
        navigateFallback: 'index.html',
      },
      manifest: {
        name: 'YesWeb',
        short_name: 'YesWeb',
        description: 'A demo of modern PWA capabilities — service workers, push, websockets, web workers, install UX.',
        id: '/',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        display_override: ['window-controls-overlay', 'standalone', 'browser'],
        orientation: 'any',
        theme_color: '#0f172a',
        background_color: '#0f172a',
        lang: 'en',
        dir: 'ltr',
        categories: ['productivity', 'developer', 'utilities'],
        icons: [
          { src: 'pwa-64x64.png',           sizes: '64x64',   type: 'image/png' },
          { src: 'pwa-96x96.png',           sizes: '96x96',   type: 'image/png' },
          { src: 'pwa-192x192.png',         sizes: '192x192', type: 'image/png' },
          { src: 'pwa-512x512.png',         sizes: '512x512', type: 'image/png' },
          { src: 'maskable-icon-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
        // Each shortcut needs its own icon for the OS jumplist. Chrome's
        // validator wants exactly 96x96 — the file is auto-generated by
        // `npm run gen:assets` via the extended preset in pwa-assets.config.ts.
        shortcuts: [
          { name: 'Status',     short_name: 'Status',   url: '/status',   description: 'Live connected clients',
            icons: [{ src: '/pwa-96x96.png', sizes: '96x96', type: 'image/png' }] },
          { name: 'Web Worker', short_name: 'Worker',   url: '/worker',   description: 'Web Worker demo',
            icons: [{ src: '/pwa-96x96.png', sizes: '96x96', type: 'image/png' }] },
          { name: 'Push',       short_name: 'Push',     url: '/push',     description: 'Web Push demo',
            icons: [{ src: '/pwa-96x96.png', sizes: '96x96', type: 'image/png' }] },
          { name: 'Manifest',   short_name: 'Manifest', url: '/manifest', description: 'PWA install playground',
            icons: [{ src: '/pwa-96x96.png', sizes: '96x96', type: 'image/png' }] },
        ],
        // Screenshots drive Chrome's richer install dialog (preview carousel).
        // Without these, Chrome falls back to the spartan one-line install
        // bar and prints "Richer PWA Install UI won't be available" warnings.
        // Files are auto-generated by `npm run gen:screenshots`; swap them for
        // real app screenshots whenever convenient — no manifest change needed.
        screenshots: [
          { src: '/screenshots/screenshot-wide.png',   sizes: '1280x720',  type: 'image/png',
            form_factor: 'wide',   label: 'YesWeb on desktop' },
          { src: '/screenshots/screenshot-narrow.png', sizes: '720x1280',  type: 'image/png',
            form_factor: 'narrow', label: 'YesWeb on mobile' },
        ],
        protocol_handlers: [{ protocol: 'web+pwademo', url: '/?proto=%s' }],
        launch_handler: { client_mode: ['navigate-existing', 'auto'] },
        edge_side_panel: { preferred_width: 480 },
        // Needed for navigator.getInstalledRelatedApps() to recognize THIS PWA
        // when the user views the site in a regular browser tab. Same-origin
        // relative URL works across dev (localhost) and prod (LAN host).
        prefer_related_applications: false,
        related_applications: [{ platform: 'webapp', url: '/manifest.webmanifest' }],
      },
    }),
  ],
  server: {
    host: true,
    port: 5173,
    strictPort: true,
    proxy: {
      '/api':       { target: 'http://localhost:3000', changeOrigin: true },
      '/socket.io': { target: 'http://localhost:3000', ws: true, changeOrigin: true },
    },
  },
  build: {
    sourcemap: true,
  },
});
