import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwind from '@tailwindcss/vite';
import { VitePWA } from 'vite-plugin-pwa';

// Build-time version stamp. A real build (`command === 'build'` — Cloud Run,
// LAN box) gets a UTC calendar build number:
//   yyyy.mm.dd.<seconds since the UTC day started>
// It's monotonic within a day and unique across days, so each deploy is
// distinguishable — the service worker's "new version → push update" flow has
// a distinct value to compare and the footer badge shows when the running
// build was cut.
//
// The local dev server (`command === 'serve'`) instead stamps a neutral
// placeholder, 0000.00.00.00000, so it's obvious you're on a local build and
// not a real deploy — the dev "version" would otherwise just be whenever you
// happened to start the server.
const DEV_VERSION = '0000.00.00.00000';
const now = new Date();
const yyyy = now.getUTCFullYear();
const mm = String(now.getUTCMonth() + 1).padStart(2, '0');
const dd = String(now.getUTCDate()).padStart(2, '0');
const secondsSinceDayStart = Math.floor(
  (now.getTime() - Date.UTC(yyyy, now.getUTCMonth(), now.getUTCDate())) / 1000,
);
const buildTime = now.toISOString();
const calendarVersion = `${yyyy}.${mm}.${dd}.${secondsSinceDayStart}`;

export default defineConfig(({ command }) => ({
  // Exposed to both the app bundle AND the service worker build — vite-plugin-pwa
  // forwards `define` into its injectManifest compile, so sw.ts can read these.
  // Keying off `command` here keeps the footer badge, the SW, and the SW
  // Lifecycle demo all agreeing on the same version.
  define: {
    __APP_VERSION__: JSON.stringify(command === 'serve' ? DEV_VERSION : calendarVersion),
    __BUILD_TIME__: JSON.stringify(buildTime),
  },
  plugins: [
    react(),
    tailwind(),
    VitePWA({
      strategies: 'injectManifest',
      srcDir: 'src',
      filename: 'sw.ts',
      // 'prompt' (not 'autoUpdate') because we drive the update ourselves from
      // lib/pwa.ts: when a new SW is waiting we show a toast, then auto-apply.
      // autoUpdate's bundled reload-on-controllerchange would race our toast.
      registerType: 'prompt',
      // We register manually via `virtual:pwa-register` in lib/pwa.ts so we get
      // the onNeedRefresh / onOfflineReady hooks and a periodic update poll —
      // the auto-injected <script> gives none of that.
      injectRegister: false,
      injectManifest: {
        // webm covers the tiny demo-video used by the PiP demo so it plays offline.
        // The manifest is intentionally NOT precached — it's served per-Host by
        // the server (apps/server/src/pwaManifest.ts) so each env gets its own
        // name + tinted icons. vite-plugin-pwa force-adds manifest.webmanifest
        // to the precache regardless of globPatterns, so the actual exclusion
        // happens in sw.ts by filtering self.__WB_MANIFEST. See the note there.
        globPatterns: ['**/*.{js,css,html,svg,png,ico,webm}'],
      },
      devOptions: {
        enabled: true,
        type: 'module',
        navigateFallback: 'index.html',
      },
      manifest: {
        name: 'YesWeb',
        short_name: 'YesWeb',
        description: 'A demo of modern PWA capabilities — service workers, push, websockets, web workers, install UX.',
        id: '/',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        display_override: ['window-controls-overlay', 'standalone', 'browser'],
        orientation: 'any',
        theme_color: '#0f172a',
        background_color: '#0f172a',
        lang: 'en',
        dir: 'ltr',
        categories: ['productivity', 'developer', 'utilities'],
        icons: [
          { src: 'pwa-64x64.png',           sizes: '64x64',   type: 'image/png' },
          { src: 'pwa-96x96.png',           sizes: '96x96',   type: 'image/png' },
          { src: 'pwa-192x192.png',         sizes: '192x192', type: 'image/png' },
          { src: 'pwa-512x512.png',         sizes: '512x512', type: 'image/png' },
          { src: 'maskable-icon-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
        // Each shortcut needs its own icon for the OS jumplist. Chrome's
        // validator wants exactly 96x96 — the file is auto-generated by
        // `npm run gen:assets` via the extended preset in pwa-assets.config.ts.
        shortcuts: [
          { name: 'Status',     short_name: 'Status',   url: '/status',   description: 'Live connected clients',
            icons: [{ src: '/pwa-96x96.png', sizes: '96x96', type: 'image/png' }] },
          { name: 'Web Worker', short_name: 'Worker',   url: '/worker',   description: 'Web Worker demo',
            icons: [{ src: '/pwa-96x96.png', sizes: '96x96', type: 'image/png' }] },
          { name: 'Push',       short_name: 'Push',     url: '/push',     description: 'Web Push demo',
            icons: [{ src: '/pwa-96x96.png', sizes: '96x96', type: 'image/png' }] },
          { name: 'Manifest',   short_name: 'Manifest', url: '/manifest', description: 'PWA install playground',
            icons: [{ src: '/pwa-96x96.png', sizes: '96x96', type: 'image/png' }] },
        ],
        // Screenshots drive Chrome's richer install dialog (preview carousel).
        // Without these, Chrome falls back to the spartan one-line install
        // bar and prints "Richer PWA Install UI won't be available" warnings.
        // Files are auto-generated by `npm run gen:screenshots`; swap them for
        // real app screenshots whenever convenient — no manifest change needed.
        screenshots: [
          { src: '/screenshots/screenshot-wide.png',   sizes: '1280x720',  type: 'image/png',
            form_factor: 'wide',   label: 'YesWeb on desktop' },
          { src: '/screenshots/screenshot-narrow.png', sizes: '720x1280',  type: 'image/png',
            form_factor: 'narrow', label: 'YesWeb on mobile' },
        ],
        protocol_handlers: [{ protocol: 'web+pwademo', url: '/?proto=%s' }],
        launch_handler: { client_mode: ['navigate-existing', 'auto'] },
        edge_side_panel: { preferred_width: 480 },
        // Needed for navigator.getInstalledRelatedApps() to recognize THIS PWA
        // when the user views the site in a regular browser tab. Same-origin
        // relative URL works across dev (localhost) and prod (LAN host).
        prefer_related_applications: false,
        related_applications: [{ platform: 'webapp', url: '/manifest.webmanifest' }],
      },
    }),
  ],
  server: {
    host: true,
    port: 5173,
    strictPort: true,
    proxy: {
      '/api':       { target: 'http://localhost:3000', changeOrigin: true },
      '/socket.io': { target: 'http://localhost:3000', ws: true, changeOrigin: true },
    },
  },
  build: {
    sourcemap: true,
  },
}));
