export type ClientInfo = {
  id: string;
  userAgent: string;
  connectedAt: number;
  lastPingMs: number | null;
};

export type PushPayload = {
  title: string;
  body: string;
  url?: string;
  actions?: { action: string; title: string }[];
};

// ────────────────────── game / lobby ──────────────────────

export type Role = 'player' | 'spectator';

export type LobbyInfo = {
  id: string;
  name: string;
  hostName: string;
  playerCount: number;
  maxPlayers: number;
  createdAt: number;
};

export type LobbyPlayer = {
  /** The player's CURRENT socket id. Regenerated by Socket.IO on every
   *  reconnect, so it's the right key for transport-level addressing (kick
   *  targeting, host identity) but the WRONG key for "is this me?" — use
   *  `clientId` for that. */
  id: string;
  /** Stable per-tab identity that survives socket reconnects. Supplied by the
   *  client in the handshake auth; falls back to the socket id for clients
   *  that don't send one (e.g. the load-test bots). The server reconciles a
   *  reconnecting player by this, and clients use it to recognize their own
   *  avatar — otherwise a pre-reconnect "ghost" record renders as a second
   *  copy of yourself until the dead socket times out. */
  clientId: string;
  displayName: string;
  character: number;
  role: Role;
  isHost: boolean;
  maxHeight: number;
};

export type LobbyState = {
  id: string;
  name: string;
  hostId: string;
  maxPlayers: number;
  createdAt: number;
  paused: boolean;
  players: LobbyPlayer[];
};

export type PlayerSnapshot = LobbyPlayer & {
  x: number;
  y: number;
  z: number;
  yaw: number;
  /** simple flag set by client when in moving/jumping state */
  state: 'idle' | 'run' | 'air';
  /** last measured round-trip ping in ms, null if not yet probed */
  ping: number | null;
};

export type GameSnapshot = {
  lobbyId: string;
  t: number;
  players: PlayerSnapshot[];
};

export type LocalInput = {
  x: number;
  y: number;
  z: number;
  yaw: number;
  state: 'idle' | 'run' | 'air';
};

export type LobbyCreate = {
  name: string;
  displayName: string;
  character: number;
  role: Role;
};

export type LobbyJoin = {
  lobbyId: string;
  displayName: string;
  character: number;
};

export type LobbyResult =
  | { ok: true; lobby: LobbyState }
  | { ok: false; error: string };

export type AdminAction =
  | { type: 'kick'; targetId: string }
  | { type: 'pause'; paused: boolean }
  | { type: 'config'; maxPlayers?: number; name?: string };

export type AdminResult = { ok: true } | { ok: false; error: string };

/** Global, fleet-wide configuration for the always-on dedicated ("Official")
 *  servers. Persisted in the `server_config` DB table (singleton row) and
 *  editable only by a token-elevated admin via the server-browser admin menu.
 *  Distinct from per-lobby {@link AdminAction} config, which mutates a single
 *  live lobby the admin is connected to. */
export type ServerConfig = {
  /** Master switch. When false, no dedicated servers run (Quick Play offline). */
  dedicatedEnabled: boolean;
  /** How many dedicated servers to keep materialized (default 1). */
  dedicatedCount: number;
  /** Player cap applied to every dedicated server (default 25). */
  dedicatedPlayerCap: number;
};

/** Defaults used by the client before the server reports the live config, and
 *  mirrored server-side in `apps/server/src/db/serverConfig.ts`. */
export const DEFAULT_SERVER_CONFIG: ServerConfig = {
  dedicatedEnabled: true,
  dedicatedCount: 1,
  dedicatedPlayerCap: 25,
};

export type ServerConfigResult =
  | { ok: true; config: ServerConfig }
  | { ok: false; error: string };

export type ServerDebugStats = {
  uptimeMs: number;
  totalLobbies: number;
  totalPlayers: number;
  tickHz: number;
  rxEvents: number;
  txEvents: number;
  rxBytesEst: number;
  txBytesEst: number;
  /** Total bytes broadcast in the most recent tick across all lobbies. The
   *  first signal a 50-player load test stresses — watch this climb. */
  lastTickBytes: number;
  /** node:perf_hooks event-loop delay percentiles in ms. Climbs above ~5ms
   *  means the loop is getting starved by tick fanout. */
  loopLagP50Ms: number;
  loopLagP99Ms: number;
  rssMb: number;
};

/** The base id of the dedicated "Official Server" family. The first dedicated
 *  server keeps this exact id (back-compat with the load-test bots and old
 *  clients); additional servers are suffixed `-2`, `-3`, … See
 *  {@link isDedicatedLobbyId}. Always-on, never dissolves, no human host
 *  (admin actions require token elevation). How many run is controlled by the
 *  admin-editable {@link ServerConfig}. Clients join via `lobby:quick-join`,
 *  which picks the least-full dedicated server. */
export const OFFICIAL_LOBBY_ID = 'tower-official';
export const OFFICIAL_HOST_ID = 'SYSTEM';

/** True for any dedicated/official-server lobby id (`tower-official` or
 *  `tower-official-N`). Used to pin them in the browser, persist their high
 *  scores, and gate admin behaviour. Mirrored server-side in
 *  `apps/server/src/game/lobby.ts` (which can't import this at runtime — the
 *  package is consumed as raw TS source; see the README). */
export function isDedicatedLobbyId(id: string): boolean {
  return id === OFFICIAL_LOBBY_ID || id.startsWith(`${OFFICIAL_LOBBY_ID}-`);
}

export type TowerHighScore = {
  displayName: string;
  character: number;
  maxHeight: number;
  achievedAt: number; // unix ms
};

/** Server tells the client what privileges (if any) the handshake earned.
 *  Emitted once on connect; client uses it to gate admin UI affordances.
 *  The server is the source of truth — a client claiming `isAdmin` without
 *  a valid ADMIN_TOKEN gets `isAdmin: false` here. */
export type AuthStatus = {
  isAdmin: boolean;
  isBot: boolean;
};

export interface ServerToClientEvents {
  'clients:update': (clients: ClientInfo[]) => void;
  'pong:reply': (sentAt: number) => void;
  'lobby:list': (lobbies: LobbyInfo[]) => void;
  'lobby:state': (state: LobbyState | null) => void;
  'game:snapshot': (snap: GameSnapshot) => void;
  'debug:server-stats': (stats: ServerDebugStats) => void;
  /** Pushed to lobby-browser room whenever the official-server leaderboard
   *  changes (player leaves, new high score posted). */
  'tower:leaderboard': (top: TowerHighScore[]) => void;
  /** Emitted once per connection after the handshake middleware runs. */
  'auth:status': (status: AuthStatus) => void;
}

export interface ClientToServerEvents {
  'status:join': () => void;
  'status:leave': () => void;
  'ping:probe': (sentAt: number) => void;
  'lobby:browser:join': () => void;
  'lobby:browser:leave': () => void;
  'lobby:create': (opts: LobbyCreate, cb: (r: LobbyResult) => void) => void;
  'lobby:join': (opts: LobbyJoin, cb: (r: LobbyResult) => void) => void;
  /** Drop into the always-on Official Server lobby in one click. Idempotent —
   *  if the caller is already in the official lobby, returns its current state. */
  'lobby:quick-join': (opts: Pick<LobbyJoin, 'displayName' | 'character'>, cb: (r: LobbyResult) => void) => void;
  'lobby:leave': () => void;
  'game:input': (input: LocalInput) => void;
  'admin:action': (action: AdminAction, cb: (r: AdminResult) => void) => void;
  /** Runtime privilege elevation — present a token, get isAdmin on success.
   *  Beats handshake auth because failure can be surfaced in the UI without
   *  a page reload. Server flips socket.data.isAdmin and re-emits auth:status. */
  'admin:elevate': (token: string, cb: (r: AdminResult) => void) => void;
  /** Drop admin privileges on this socket. No-op if not currently elevated. */
  'admin:logout': (cb: (r: AdminResult) => void) => void;
  /** Read the global dedicated-server config (admin only). Used by the
   *  server-browser admin menu to populate its form. */
  'admin:get-config': (cb: (r: ServerConfigResult) => void) => void;
  /** Update the global dedicated-server config (admin only). The server
   *  persists it, reconciles the live dedicated lobbies (spawning/removing
   *  servers, re-capping players), and acks the clamped result. */
  'admin:set-config': (patch: Partial<ServerConfig>, cb: (r: ServerConfigResult) => void) => void;
  'debug:subscribe': () => void;
  'debug:unsubscribe': () => void;
}

export type AnySocketEvent =
  | keyof ServerToClientEvents
  | keyof ClientToServerEvents;
